---
- hosts: default
  become_user: root
  become_method: sudo
  become: yes

  vars:
    project_dir: '/var/www/pedasi'
    venv_dir: '{{ project_dir }}/env'
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Check if running under Vagrant
      stat:
        path: /vagrant
      register: vagrant_dir

  roles:
    - database
    - webserver