---
deploy_mode_dict:
  1: Production
  2: Staging
  3: Development
deploy_mode: 3

secret_key: "{{ lookup('password', '/tmp/secretkeyfile') }}"

project_dir: '/var/www/pedasi'
venv_dir: '{{ project_dir }}/env'

web_user: '{{ "www-data" if ansible_distribution == "Ubuntu" else "nginx" }}'

###########################################
# Null values to override in inventory file

# Email configuration
email_host_password:
default_from_email:
admin_name:
admin_email:

# Google OAuth2
oauth2_key:
oauth2_secret:
