---
- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
    enabled: yes

- name: restart mongod
  service:
    name: mongod
    state: restarted
    enabled: yes